# SPDX-License-Identifier: GPL-2.0-only
# Makefile for the Linux affs filesystem routines.

#ccflags-y := -DDEBUG=1
obj-$(CONFIG_AFFS_FS) += affs.o
affs-objs := amigaffs.o bitmap.o dir.o file.o inode.o namei.o super.o symlink.o
